apiVersion: v1
kind: Service
metadata:
  name: course-app-service
  labels:
    app: course-app
spec:
  type: ClusterIP
  selector:
    app: course-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
